
-- Tabela de Produtos
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price decimal(10,2) not null,
  image_url text,
  category text,
  stock integer default 0
);

-- Tabela de Serviços (Banho, Tosa, etc.)
create table services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price decimal(10,2) not null,
  duration_minutes integer not null default 60
);

-- Tabela de Agendamentos
create table appointments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  client_phone text,
  pet_name text not null,
  service_id bigint references services(id),
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null, -- Calculado base na duração
  status text default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  notes text
);

-- Políticas de Segurança (RLS) - Simples para começar
alter table products enable row level security;
create policy "Public Products are viewable by everyone" on products for select using (true);

alter table services enable row level security;
create policy "Public Services are viewable by everyone" on services for select using (true);

alter table appointments enable row level security;
create policy "Anyone can create appointments" on appointments for insert with check (true);
create policy "Public Appointments viewable" on appointments for select using (true);
